<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8G3MUB9" ignored="0" name="Iteration3" tests="4" failures="1" timestamp="2021-03-10T22:10:20 IST" time="48.36" errors="0">
  <testcase name="launch" time="19.754" classname="Tests.LoginTestwithXml"/>
  <testcase name="uidTest" time="27.388" classname="Tests.LoginTestwithXml">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Tests.LoginTestwithXml.uidTest(LoginTestwithXml.java:84)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- uidTest -->
  <testcase name="pwdTest" time="0.0" classname="Tests.LoginTestwithXml">
    <skipped/>
  </testcase> <!-- pwdTest -->
  <testcase name="close" time="1.117" classname="Tests.LoginTestwithXml"/>
</testsuite> <!-- Iteration3 -->
